# Generated by Django 5.2 on 2025-10-12 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='none', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'status',
            },
        ),
        migrations.CreateModel(
            name='Abudhabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('topview', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('network_status', models.CharField(default='GOOD', max_length=50)),
                ('printer_status', models.CharField(default='GOOD', max_length=50)),
                ('AI_Cam', models.CharField(default='GOOD', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lasvegas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('topview', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('network_status', models.CharField(default='GOOD', max_length=50)),
                ('printer_status', models.CharField(default='GOOD', max_length=50)),
                ('AI_Cam', models.CharField(default='GOOD', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('topview', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('network_status', models.CharField(default='GOOD', max_length=50)),
                ('printer_status', models.CharField(default='GOOD', max_length=50)),
                ('AI_Cam', models.CharField(default='GOOD', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.CharField(choices=[('las_vegas', 'Las Vegas'), ('monaco', 'Monaco'), ('suzuka', 'Suzuka'), ('abudhabi', 'Abu Dhabi')], max_length=20)),
                ('file', models.FileField(upload_to='obstacles/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='obstacle_images/')),
                ('details', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('specific_backup', models.IntegerField(default=5)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=200, null=True)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('requirement_las_vegas', models.CharField(blank=True, max_length=200, null=True)),
                ('propose_spare_las_vegas', models.CharField(blank=True, max_length=200, null=True)),
                ('requirement_abu_dhabi', models.CharField(blank=True, max_length=200, null=True)),
                ('propose_spare_abu_dhabi', models.CharField(blank=True, max_length=200, null=True)),
                ('requirement_monaco', models.CharField(blank=True, max_length=200, null=True)),
                ('propose_spare_monaco', models.CharField(blank=True, max_length=200, null=True)),
                ('requirement_suzuka', models.CharField(blank=True, max_length=200, null=True)),
                ('propose_spare_suzuka', models.CharField(blank=True, max_length=200, null=True)),
                ('c1_requirement_las_vegas', models.CharField(blank=True, max_length=200, null=True)),
                ('c1_propose_spare_las_vegas', models.CharField(blank=True, max_length=200, null=True)),
                ('c2_requirement_abu_dhabi', models.CharField(blank=True, max_length=200, null=True)),
                ('c2_propose_spare_abu_dhabi', models.CharField(blank=True, max_length=200, null=True)),
                ('c4_requirement_monaco', models.CharField(blank=True, max_length=200, null=True)),
                ('c4_propose_spare_monaco', models.CharField(blank=True, max_length=200, null=True)),
                ('c3_requirement_suzuka', models.CharField(blank=True, max_length=200, null=True)),
                ('c3_propose_spare_suzuka', models.CharField(blank=True, max_length=200, null=True)),
                ('it_room_requirements', models.CharField(blank=True, max_length=200, null=True)),
                ('it_room_propose_spare', models.CharField(blank=True, max_length=200, null=True)),
                ('it_room_storage_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('it_room_storage_propose_spare', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_1_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_1_propose_spare', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_hr_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_hr_propose_spare', models.CharField(blank=True, max_length=200, null=True)),
                ('hallway_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('hallway_propose_spare', models.CharField(blank=True, max_length=200, null=True)),
                ('commentator_pantry_requirement', models.CharField(blank=True, max_length=200, null=True)),
                ('commentator_pantry_propose_spare', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.room')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.status')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='SpecificItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inUse', 'In Use'), ('readyForDeployment', 'Ready for Deployment'), ('backup/Stock', 'Backup/Stock'), ('orderedWaitingForShipment', 'Order waiting for shipment'), ('requested,NotYetPlaceOrder', 'Requested,not yet place order'), ('broken', 'Broken'), ('resell', 'Resell')], default='None', max_length=50)),
                ('quantity_added', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('serial', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_items', to='inventory.inventoryitem')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.room')),
            ],
        ),
        migrations.CreateModel(
            name='Suzuka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('topview', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('network_status', models.CharField(default='GOOD', max_length=50)),
                ('printer_status', models.CharField(default='GOOD', max_length=50)),
                ('AI_Cam', models.CharField(default='GOOD', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
