# Generated by Django 5.2 on 2025-10-13 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_specificitem_last_modified_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.CharField(max_length=100)),
                ('equipment_name', models.CharField(max_length=100)),
                ('check_time', models.TimeField()),
                ('check_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submission_group_id', models.CharField(help_text='Identifier to group all items from a single submission', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
