# Generated by Django 5.2.7 on 2025-10-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_checklistsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='propose_spare_3d_dept',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='propose_spare_ph_studio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='propose_spare_seven_floor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requirement_3d_dept',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requirement_ph_studio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requirement_seven_floor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
