# Generated by Django 5.2.7 on 2025-12-12 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_propose_spare_3d_dept_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Philippines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('topview', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('network_status', models.CharField(default='GOOD', max_length=50)),
                ('printer_status', models.CharField(default='GOOD', max_length=50)),
                ('AI_Cam', models.CharField(default='GOOD', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plinko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('topview', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
                ('audio', models.CharField(max_length=50)),
                ('camera', models.CharField(max_length=50)),
                ('network_status', models.CharField(default='GOOD', max_length=50)),
                ('printer_status', models.CharField(default='GOOD', max_length=50)),
                ('AI_Cam', models.CharField(default='GOOD', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
