# Generated by Django 5.2.7 on 2025-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_philippines_plinko'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='propose_spare_mini_pitx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requirement_mini_pitx',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
