# Generated by Django 5.2.7 on 2026-01-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_propose_spare_mini_pitx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='propose_spare_plinko',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='requirement_plinko',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
